controller:
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
#      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:178724175855:certificate/20de0380-7c97-4be2-9e8b-080af278044a
#      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tls"
#      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"